server:
  port: 20000
spring:
  application:
    name: producer
  cloud:
    nacos:
#      config:
#        server-addr: 192.168.60.10:8848
#        username: nacos
#        password: nacos
#        namespace: dev
      discovery:
        server-addr: 192.168.60.10:8848
        username: nacos
        password: nacos
        namespace: dev
  #  config:
  #    import:
  #      - optional:nacos:producer.yml
  data:
    redis:
      host: 192.168.60.10
      password: 666
      database: 0
  datasource:
    #    druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.60.10:3306/consumer?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 666
  rabbitmq:
      addresses: 192.168.60.10:5672
      username: root
      password: 666
      virtual-host: /
      publisher-returns: true
      publisher-confirm-type: correlated